### ISSUE TITLE
How does it do on test262?

### ISSUE THREAD

**Issue by erights** [ASDAlexander77/TypeScript2Cxx#1]

**Comment by ASDAlexander77** [comment]
test262 is for JSVM and JavaScript.  There are some test which can be used.  But TypeScript2Cxx is not for JSVM conformance

**Comment by erights** [comment]
How does TypeScript itself do on test262? How does TypeScript2Cxx compare to TypeScript re test262?

**Comment by ASDAlexander77** [comment]
> How does TypeScript itself do on test262? How does TypeScript2Cxx compare to TypeScript re test262?

I will have a look which tests I can reuse

**Comment by ASDAlexander77** [comment]
i have added tests from Static TypeScript. it is looking good. Minor issues at that moment
