### ISSUE TITLE
Installing fails

### ISSUE THREAD

**Issue by indymx** [ASDAlexander77/TypeScript2Cxx#13]
followed instructions on github, got this result:
```
terry@serge:~/TypeScript2Cxx$ npm install

> typescript_cxx@1.0.0 prepublish
> prepublish_npm.cmd

sh: 1: prepublish_npm.cmd: not found
npm ERR! code 127
npm ERR! path /home/terry/TypeScript2Cxx
npm ERR! command failed
npm ERR! command sh -c prepublish_npm.cmd

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/terry/.npm/_logs/2022-03-09T11_23_06_974Z-debug-0.log


terry@serge:~/TypeScript2Cxx$ ls
cpplib  Experiment  node_modules  __out  package.json  package-lock.json  packages  prepublish_npm.cmd  README.md  spec  src  test  test.ts  tsconfig.json  tslint.json  typescript2cxx.code-workspace
```

File is clearly there...

**Comment by bodyo** [comment]
I have got the same issue.

`~/repo/TypeScript2Cxx  master ✔                                                                                                                                                            1y47d
▶ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

> typescript_cxx@1.0.0 prepublish
> prepublish_npm.cmd

sh: prepublish_npm.cmd: command not found
npm ERR! code 127
npm ERR! path /Users/bodyo/repo/TypeScript2Cxx
npm ERR! command failed
npm ERR! command sh -c -- prepublish_npm.cmd

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bodyo/.npm/_logs/2022-08-17T20_37_44_520Z-debug-0.log

~/repo/TypeScript2Cxx  master ✗                                                                                                                                                         1y47d ⚑  ⍉
▶ npm -v
8.17.0

~/repo/TypeScript2Cxx  master ✗                                                                                                                                                          1y47d ⚑
▶ node -v
v17.8.0`
