### ISSUE TITLE
Function return types and N-API

### ISSUE THREAD

**Issue by Downchuck** [ASDAlexander77/TypeScript2Cxx#18]
I am manually generating bindings.cc for Node API, with two notes in mind:
- The extension ecosystem (node.js, deno, bun) has agreed on supporting Node-API.
- Typescript correctly infers the return type in the example "ElevatorPitch" as string, 

Function headers are trivial using node-addons-api in C++, it's the return statement that has me wondering:

```
Napi::Value ElevatorPitch(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  return Napi::String::New(env, impl->ElevatorPitch());
}
```

My questions:
- Should ElevatorPitch in generated TypeScript2Cxx be any or should it have a more specific type decorator?
- If it should remain as any, what's the better way to inline cast, as it's going to be wrapped again anyway

Is it just
```
js::string(impl->ElevatorPitch())
```

-Charles

**Comment by ASDAlexander77** [comment]
Defenetly it is better to use js::string instead of js::any. so u can add type cast in TS file like 
```TypeScript
let o = <string>howard.ElevatorPitch;
```

or you can add type into return function

```TypeScript
    public get ElevatorPitch(): string {
        return `Hello, my name is ${this.name} and I work in ${this.department}.`;
    }
```

**Comment by Downchuck** [comment]
Thanks! It does look like explicit return types are the right way to go.

I hoped Typescript's type inference on return types would help avoid explicit return types, but it has quirks on private members.

So, for some random facts about trying to use typescript decorator files (d.ts):

```sh
$ yarn exec tsc -- -t esnext -d --emitDeclarationOnly test.ts
```

Type is dropped on private and #private for technical reasons:

```ts
declare class Employee extends Person {
    private department;
    constructor(name: string, department: string);
    get ElevatorPitch(): string;
}
```

When using ECMAScript #private, field names are dropped altogether:

```ts
declare class Employee extends Person {
    #private;
    constructor(name: string, department: string);
    get ElevatorPitch(): string;
}
```

So it does a great job of inference but, correctly (for its purpose), drops type data for private fields.
