### ISSUE TITLE
Installing from NPM doesn't work

### ISSUE THREAD

**Issue by jarble** [ASDAlexander77/TypeScript2Cxx#9]
I tried to install this package from NPM:

`npm install typescript_cxx`

But it seems that `typescript_cxx` hasn't been added to the NPM package registry.

Can this compiler be added to the registry, to allow easier installation?

**Comment by ASDAlexander77** [comment]
I removed it from npm, as no one was using it so far.

**Comment by jarble** [comment]
I wish it were still available on NPM: I wanted to install this package without manually copying the Github repository.
